export { default as Home } from "./home";
export { default as Users } from "./users";
export { default as Posts } from "./posts/posts";
export { default as PostDetail } from "./posts/postDetail";
export { default as Gallery } from "./gallery/gallery";
export { default as Photos } from "./gallery/photos";
export { default as Todos } from "./todos/todos";
export { default as Pending } from "./todos/pending";
export { default as Completed } from "./todos/completed";
